spring:
  application:
    name: web-all
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.6.100:8848
      config:
        server-addr: 192.168.6.100:8848
